name: build

on:
  push:
    branches: [ master ]

jobs:
  cache:
    runs-on: ubuntu-latest
    name: Cache dependencies

    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        id: cache-m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 1.8
        if: steps.cache-m2.outputs.cache-hit != 'true'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests with Maven
        if: steps.cache-m2.outputs.cache-hit != 'true'
        run: mvn -B dependency:go-offline

  coverage:
    runs-on: ubuntu-latest
    name: Jacoco analysis (Java 8)
    needs: [ cache ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Load Cached m2
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Run tests with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.0

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'deploy-serval-snt'
            git config --global user.email 'deploy.serval.snt@gmail.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi

  sonarcloud:
    runs-on: ubuntu-latest
    name: Sonar analysis (Java 11)
    needs: [ cache ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Load Cached m2
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar